### ISSUE TITLE
Sort without animation?

### ISSUE THREAD

**Issue by beckend** [quintana-dev/sortboard#7]
Sometimes I want to reset the sorting when the container is hidden, then sorting instantly would make sense.

**Comment by joseluisq** [comment]
**Sortboard** doesn't use some animation.
For example, [In the demo](http://codepen.io/joseluisq/full/IlHzo/) the animation occurs but 
**I defined** (intentionally) a `transtion` css property for animate `li` blocks.

```css
#sortlist li {
  transition: all 0.4s ease-out;
}
```

Simply you should remove your `transition` property of your css. 
For example using javascript for prevent animation on the fly.
